import {
  RACE_MODE_RESPAWN_DELAY_TICKS_V1,
  KZ_ROUTE_BRANCH_ROLE,
  KZ_ROUTE_DEFINITION_SCHEMA_VERSION,
  KZ_ROUTE_HIT_RECOVERY,
  KZ_ROUTE_INPUT,
  KZ_ROUTE_RESPONSE_OPTION,
  KZ_ROUTE_SEGMENT_KIND,
  KZ_ROUTE_SURVIVAL_ROLE,
  MAP_DEFINITION_SCHEMA_VERSION,
  createKzRouteDefinitionV2,
  createMapDefinition,
  type KzRouteDifficultyV2,
  type Vector3Definition,
} from '@number-strategy-jump/arena-definitions';
import {
  validateKzRouteMapCandidateV1,
  type KzRouteMobilityEnvelopeV1,
} from '@number-strategy-jump/arena-map';
import {
  ARENA_V2_RACE_FINISH_GATE_CAPABILITY_ID_V1,
} from './arena-v2-race-finish-capability-id-v1.js';
import {
  ARENA_V2_RACE_RESPAWN_FALLBACK_SAFE_ANCHOR_CAPABILITY_ID_V1,
} from './arena-v2-race-respawn-capability-id-v1.js';
import {
  ARENA_V2_SURVIVAL_PLAYER_RESPAWN_SAFE_ANCHOR_CAPABILITY_ID_V1,
} from './arena-v2-survival-respawn-capability-id-v1.js';

export const ARENA_V2_KZ_BASE_MAP_CANDIDATE_ID = 'arena-v2-kz-base-map.candidate.v1';
export const ARENA_V2_KZ_BASE_ROUTE_CANDIDATE_ID = 'arena-v2-kz-base-route.candidate.v2';

const surface = (
  id: string,
  center: Vector3Definition,
  halfExtents: Vector3Definition,
) => Object.freeze({ id, center: Object.freeze(center), halfExtents: Object.freeze(halfExtents) });

const SURFACES = Object.freeze([
  surface('kz-s01-start', { x: 0, y: 0, z: 0 }, { x: 3.2, y: 0.5, z: 2.4 }),
  surface('kz-s02-landing', { x: 7, y: 0, z: 0 }, { x: 1.8, y: 0.5, z: 2 }),
  surface('kz-s03-stair-a', { x: 10.2, y: 0.15, z: 0 }, { x: 1.2, y: 0.5, z: 1.6 }),
  surface('kz-s03-stair-b', { x: 12.8, y: 0.3, z: 0 }, { x: 1.2, y: 0.5, z: 1.6 }),
  surface('kz-s03-stair-c', { x: 15.4, y: 0.45, z: 0 }, { x: 1.2, y: 0.5, z: 1.6 }),
  surface('kz-s04-fast-a', { x: 18.2, y: 0.45, z: 0 }, { x: 1.4, y: 0.5, z: 1.3 }),
  surface('kz-s04-fast-b', { x: 20.8, y: 0.45, z: -2.2 }, { x: 1.3, y: 0.5, z: 1.3 }),
  surface('kz-s04-safe-a', { x: 18, y: 0.75, z: 1.8 }, { x: 1.4, y: 0.5, z: 1.4 }),
  surface('kz-s04-safe-b', { x: 20.8, y: 0.75, z: 1.8 }, { x: 1.4, y: 0.5, z: 1.4 }),
  surface('kz-s04-safe-c', { x: 23.4, y: 0.6, z: 0 }, { x: 1.4, y: 0.5, z: 1.4 }),
  surface('kz-s04-merge', { x: 23.4, y: 0.45, z: -2.2 }, { x: 1.4, y: 0.5, z: 1.3 }),
  surface('kz-s05-narrow', { x: 26.6, y: 0.45, z: -2.2 }, { x: 1.7, y: 0.5, z: 0.5 }),
  surface('kz-s06-safe-a', { x: 29.1, y: 0.45, z: -1.2 }, { x: 1, y: 0.5, z: 0.55 }),
  surface('kz-s06-safe-b', { x: 31.3, y: 0.45, z: -2.9 }, { x: 1, y: 0.5, z: 0.55 }),
  surface('kz-s06-safe-c', { x: 33.5, y: 0.45, z: -1.2 }, { x: 1, y: 0.5, z: 0.55 }),
  surface('kz-s06-fast-wire', { x: 31.6, y: 0.45, z: -2.2 }, { x: 3.3, y: 0.5, z: 0.28 }),
  surface('kz-s06-finish', { x: 36.2, y: 0.45, z: -2.2 }, { x: 1.5, y: 0.5, z: 1.2 }),
  surface('kz-s07-breather', { x: 40.3, y: 0.45, z: -2.2 }, { x: 1.4, y: 0.5, z: 1.6 }),
  surface('kz-s08-stair-a', { x: 43.5, y: 0.65, z: -2.2 }, { x: 1, y: 0.5, z: 1.3 }),
  surface('kz-s08-stair-b', { x: 45.8, y: 0.85, z: -2.2 }, { x: 1, y: 0.5, z: 1.3 }),
  surface('kz-s08-stair-c', { x: 48.1, y: 1.05, z: -2.2 }, { x: 1, y: 0.5, z: 1.2 }),
  surface('kz-s09-fast-a', { x: 51.2, y: 1.05, z: -3.4 }, { x: 1.1, y: 0.5, z: 0.7 }),
  surface('kz-s09-fast-b', { x: 53.6, y: 1.05, z: -3.4 }, { x: 1, y: 0.5, z: 0.55 }),
  surface('kz-s09-safe-a', { x: 51.2, y: 1.25, z: -0.8 }, { x: 1.1, y: 0.5, z: 1 }),
  surface('kz-s09-safe-b', { x: 53.6, y: 1.25, z: -0.8 }, { x: 1.1, y: 0.5, z: 1 }),
  surface('kz-s09-safe-c', { x: 55.8, y: 1.1, z: -2.1 }, { x: 1.1, y: 0.5, z: 1 }),
  surface('kz-s09-merge', { x: 56, y: 1.05, z: -3.4 }, { x: 1.2, y: 0.5, z: 0.7 }),
  surface('kz-s10-landing', { x: 60.5, y: 1.05, z: -3.4 }, { x: 1.5, y: 0.5, z: 1 }),
  surface('kz-s11-narrow', { x: 64.5, y: 1.05, z: -3.4 }, { x: 1.4, y: 0.5, z: 0.35 }),
  surface('kz-s12-safe-a', { x: 67.6, y: 1.05, z: -2 }, { x: 0.9, y: 0.5, z: 0.5 }),
  surface('kz-s12-safe-b', { x: 69.8, y: 1.05, z: -1 }, { x: 0.9, y: 0.5, z: 0.5 }),
  surface('kz-s12-safe-c', { x: 72, y: 1.05, z: -2 }, { x: 0.9, y: 0.5, z: 0.5 }),
  surface('kz-s12-fast-wire', { x: 69.5, y: 1.05, z: -3.4 }, { x: 3, y: 0.5, z: 0.22 }),
  surface('kz-s12-finish', { x: 75, y: 1.05, z: -3.4 }, { x: 1.5, y: 0.5, z: 1.1 }),
]);

const anchor = (id: string, surfaceId: string, x: number, y: number, z: number) => Object.freeze({
  id,
  surfaceId,
  position: Object.freeze({ x, y, z }),
});

const ANCHORS = Object.freeze([
  anchor('kz-a-start-1', 'kz-s01-start', -1.8, 0.5, -1.5),
  anchor('kz-a-start-2', 'kz-s01-start', -1.8, 0.5, -0.5),
  anchor('kz-a-start-3', 'kz-s01-start', -1.8, 0.5, 0.5),
  anchor('kz-a-start-4', 'kz-s01-start', -1.8, 0.5, 1.5),
  anchor('kz-a-route-start', 'kz-s01-start', -2.4, 0.5, 0),
  anchor(
    ARENA_V2_RACE_RESPAWN_FALLBACK_SAFE_ANCHOR_CAPABILITY_ID_V1,
    'kz-s01-start',
    -2.4,
    0.5,
    0,
  ),
  anchor(
    ARENA_V2_SURVIVAL_PLAYER_RESPAWN_SAFE_ANCHOR_CAPABILITY_ID_V1,
    'kz-s01-start',
    -2.4,
    0.5,
    0,
  ),
  anchor('kz-a-s01-supply', 'kz-s01-start', 0, 0.5, 1.4),
  anchor('kz-a-s01-exit', 'kz-s01-start', 2.9, 0.5, 0),
  anchor('kz-a-s02-supply', 'kz-s02-landing', 7, 0.5, 1.1),
  anchor('kz-a-s02-exit', 'kz-s02-landing', 8.5, 0.5, 0),
  anchor('kz-a-s03-a', 'kz-s03-stair-a', 10.2, 0.65, 0),
  anchor('kz-a-s03-b', 'kz-s03-stair-b', 12.8, 0.8, 0),
  anchor('kz-a-s03-supply', 'kz-s03-stair-b', 12.8, 0.8, 1),
  anchor('kz-a-s03-exit', 'kz-s03-stair-c', 15.9, 0.95, 0),
  anchor('kz-a-s04-fast-a', 'kz-s04-fast-a', 18.2, 0.95, 0),
  anchor('kz-a-s04-fast-b', 'kz-s04-fast-b', 20.8, 0.95, -2.2),
  anchor('kz-a-s04-safe-a', 'kz-s04-safe-a', 18, 1.25, 1.8),
  anchor('kz-a-s04-safe-b', 'kz-s04-safe-b', 20.8, 1.25, 1.8),
  anchor('kz-a-s04-safe-c', 'kz-s04-safe-c', 23.4, 1.1, 0),
  anchor('kz-a-s04-supply', 'kz-s04-safe-b', 20.8, 1.25, 2.5),
  anchor('kz-a-s04-exit', 'kz-s04-merge', 24.5, 0.95, -2.2),
  anchor('kz-a-s05-supply', 'kz-s05-narrow', 26.6, 0.95, -2.2),
  anchor('kz-a-s05-exit', 'kz-s05-narrow', 28.1, 0.95, -2.2),
  anchor('kz-a-s06-safe-a', 'kz-s06-safe-a', 29.1, 0.95, -1.2),
  anchor('kz-a-s06-safe-b', 'kz-s06-safe-b', 31.3, 0.95, -2.9),
  anchor('kz-a-s06-safe-c', 'kz-s06-safe-c', 33.5, 0.95, -1.2),
  anchor('kz-a-s06-fast', 'kz-s06-fast-wire', 31.6, 0.95, -2.2),
  anchor('kz-a-s06-supply', 'kz-s06-safe-a', 29.1, 0.95, -1.2),
  anchor('kz-a-s06-exit', 'kz-s06-finish', 36.2, 0.95, -2.2),
  anchor('kz-a-s07-supply', 'kz-s07-breather', 39.5, 0.95, -1.4),
  anchor('kz-a-s07-exit', 'kz-s07-breather', 41.4, 0.95, -2.2),
  anchor('kz-a-s08-a', 'kz-s08-stair-a', 43.5, 1.15, -2.2),
  anchor('kz-a-s08-b', 'kz-s08-stair-b', 45.8, 1.35, -2.2),
  anchor('kz-a-s08-supply', 'kz-s08-stair-b', 45.8, 1.35, -1.3),
  anchor('kz-a-s08-exit', 'kz-s08-stair-c', 48.8, 1.55, -2.2),
  anchor('kz-a-s09-fast-a', 'kz-s09-fast-a', 51.2, 1.55, -3.4),
  anchor('kz-a-s09-fast-b', 'kz-s09-fast-b', 53.6, 1.55, -3.4),
  anchor('kz-a-s09-safe-a', 'kz-s09-safe-a', 51.2, 1.75, -0.8),
  anchor('kz-a-s09-safe-b', 'kz-s09-safe-b', 53.6, 1.75, -0.8),
  anchor('kz-a-s09-safe-c', 'kz-s09-safe-c', 55.8, 1.6, -2.1),
  anchor('kz-a-s09-supply', 'kz-s09-safe-b', 53.6, 1.75, 0),
  anchor('kz-a-s09-exit', 'kz-s09-merge', 56.8, 1.55, -3.4),
  anchor('kz-a-s10-supply', 'kz-s10-landing', 60.5, 1.55, -2.7),
  anchor('kz-a-s10-exit', 'kz-s10-landing', 61.6, 1.55, -3.4),
  anchor('kz-a-s11-supply', 'kz-s11-narrow', 64.5, 1.55, -3.4),
  anchor('kz-a-s11-exit', 'kz-s11-narrow', 65.6, 1.55, -3.4),
  anchor('kz-a-s12-safe-a', 'kz-s12-safe-a', 67.6, 1.55, -2),
  anchor('kz-a-s12-safe-b', 'kz-s12-safe-b', 69.8, 1.55, -1),
  anchor('kz-a-s12-safe-c', 'kz-s12-safe-c', 72, 1.55, -2),
  anchor('kz-a-s12-fast', 'kz-s12-fast-wire', 69.5, 1.55, -3.4),
  anchor('kz-a-s12-supply', 'kz-s12-safe-a', 67.6, 1.55, -2),
  anchor('kz-a-finish', 'kz-s12-finish', 75, 1.55, -3.4),
]);

const difficulty = (
  distance: number,
  rhythm: number,
  turn: number,
  route: number,
  recovery: number,
  combat: number,
): KzRouteDifficultyV2 => Object.freeze({ distance, rhythm, turn, route, recovery, combat });

export const ARENA_V2_KZ_BASE_MAP_DEFINITION_CANDIDATE_V1 = createMapDefinition({
  schemaVersion: MAP_DEFINITION_SCHEMA_VERSION,
  id: ARENA_V2_KZ_BASE_MAP_CANDIDATE_ID,
  arena: {
    killY: -6,
    surfaces: SURFACES,
    spawns: [
      { x: -1.8, y: 1.5, z: -1.5 },
      { x: -1.8, y: 1.5, z: -0.5 },
      { x: -1.8, y: 1.5, z: 0.5 },
      { x: -1.8, y: 1.5, z: 1.5 },
    ],
  },
  equipmentSpawnPoints: [
    { id: 'kz-supply-01', surfaceId: 'kz-s01-start', position: { x: 0, y: 0.5, z: 1.4 } },
    { id: 'kz-supply-02', surfaceId: 'kz-s02-landing', position: { x: 7, y: 0.5, z: 1.1 } },
    { id: 'kz-supply-03', surfaceId: 'kz-s03-stair-b', position: { x: 12.8, y: 0.8, z: 1 } },
    { id: 'kz-supply-04', surfaceId: 'kz-s04-safe-b', position: { x: 20.8, y: 1.25, z: 2.5 } },
    { id: 'kz-supply-05', surfaceId: 'kz-s05-narrow', position: { x: 26.6, y: 0.95, z: -2.2 } },
    { id: 'kz-supply-06', surfaceId: 'kz-s06-safe-a', position: { x: 29.1, y: 0.95, z: -1.2 } },
    { id: 'kz-supply-07', surfaceId: 'kz-s07-breather', position: { x: 39.5, y: 0.95, z: -1.4 } },
    { id: 'kz-supply-08', surfaceId: 'kz-s08-stair-b', position: { x: 45.8, y: 1.35, z: -1.3 } },
    { id: 'kz-supply-09', surfaceId: 'kz-s09-safe-b', position: { x: 53.6, y: 1.75, z: 0 } },
    { id: 'kz-supply-10', surfaceId: 'kz-s10-landing', position: { x: 60.5, y: 1.55, z: -2.7 } },
    { id: 'kz-supply-11', surfaceId: 'kz-s11-narrow', position: { x: 64.5, y: 1.55, z: -3.4 } },
    { id: 'kz-supply-12', surfaceId: 'kz-s12-safe-a', position: { x: 67.6, y: 1.55, z: -2 } },
  ],
  events: [],
});

export const ARENA_V2_KZ_BASE_ROUTE_DEFINITION_CANDIDATE_V2 = createKzRouteDefinitionV2({
  schemaVersion: KZ_ROUTE_DEFINITION_SCHEMA_VERSION,
  id: ARENA_V2_KZ_BASE_ROUTE_CANDIDATE_ID,
  mapDefinitionId: ARENA_V2_KZ_BASE_MAP_CANDIDATE_ID,
  requiredInputs: [KZ_ROUTE_INPUT.DIRECTION, KZ_ROUTE_INPUT.JUMP],
  minimumParticipants: 2,
  maximumParticipants: 4,
  respawnDelayTicks: RACE_MODE_RESPAWN_DELAY_TICKS_V1,
  startAnchorIds: ['kz-a-start-1', 'kz-a-start-2', 'kz-a-start-3', 'kz-a-start-4'],
  finishAnchorId: 'kz-a-finish',
  anchors: ANCHORS,
  segments: [
    {
      id: 'kz-segment-01-platform', kind: KZ_ROUTE_SEGMENT_KIND.BASIC_PLATFORM,
      lessonId: 'kz.lesson.jump-distance', remixId: 'kz.remix.short-chain',
      surfaceIds: ['kz-s01-start'], pathAnchorIds: ['kz-a-route-start', 'kz-a-s01-exit'],
      entryAnchorId: 'kz-a-route-start', exitAnchorId: 'kz-a-s01-exit',
      respawnAnchorId: ARENA_V2_RACE_RESPAWN_FALLBACK_SAFE_ANCHOR_CAPABILITY_ID_V1,
      survivalRole: KZ_ROUTE_SURVIVAL_ROLE.SAFE,
      responseOptions: [KZ_ROUTE_RESPONSE_OPTION.HOLD, KZ_ROUTE_RESPONSE_OPTION.STRAFE, KZ_ROUTE_RESPONSE_OPTION.JUMP],
      responseWindowTicks: 10, hitRecovery: KZ_ROUTE_HIT_RECOVERY.SAME_SEGMENT,
      difficulty: difficulty(1, 1, 1, 1, 1, 1), branches: [],
    },
    {
      id: 'kz-segment-02-gap', kind: KZ_ROUTE_SEGMENT_KIND.GAP,
      lessonId: 'kz.lesson.commit-direction', remixId: 'kz.remix.air-correction',
      surfaceIds: ['kz-s02-landing'], pathAnchorIds: ['kz-a-s01-exit', 'kz-a-s02-exit'],
      entryAnchorId: 'kz-a-s01-exit', exitAnchorId: 'kz-a-s02-exit',
      respawnAnchorId: 'kz-a-s01-exit', survivalRole: KZ_ROUTE_SURVIVAL_ROLE.RECOVERY,
      responseOptions: [KZ_ROUTE_RESPONSE_OPTION.JUMP], responseWindowTicks: 8,
      hitRecovery: KZ_ROUTE_HIT_RECOVERY.RESPAWN_ANCHOR,
      difficulty: difficulty(2, 2, 2, 1, 2, 1), branches: [],
    },
    {
      id: 'kz-segment-03-stairs', kind: KZ_ROUTE_SEGMENT_KIND.STAIRS,
      lessonId: 'kz.lesson.jump-rhythm', remixId: 'kz.remix.three-step-chain',
      surfaceIds: ['kz-s03-stair-a', 'kz-s03-stair-b', 'kz-s03-stair-c'],
      pathAnchorIds: ['kz-a-s02-exit', 'kz-a-s03-a', 'kz-a-s03-b', 'kz-a-s03-exit'],
      entryAnchorId: 'kz-a-s02-exit', exitAnchorId: 'kz-a-s03-exit',
      respawnAnchorId: 'kz-a-s02-exit', survivalRole: KZ_ROUTE_SURVIVAL_ROLE.PRESSURE,
      responseOptions: [KZ_ROUTE_RESPONSE_OPTION.STRAFE, KZ_ROUTE_RESPONSE_OPTION.JUMP],
      responseWindowTicks: 10, hitRecovery: KZ_ROUTE_HIT_RECOVERY.ADJACENT_SEGMENT,
      difficulty: difficulty(2, 3, 2, 1, 2, 2), branches: [],
    },
    {
      id: 'kz-segment-04-maze', kind: KZ_ROUTE_SEGMENT_KIND.MAZE,
      lessonId: 'kz.lesson.read-route', remixId: 'kz.remix.fast-or-recovery',
      surfaceIds: ['kz-s04-fast-a', 'kz-s04-fast-b', 'kz-s04-safe-a', 'kz-s04-safe-b', 'kz-s04-safe-c', 'kz-s04-merge'],
      pathAnchorIds: ['kz-a-s03-exit', 'kz-a-s04-fast-a', 'kz-a-s04-fast-b', 'kz-a-s04-exit'],
      entryAnchorId: 'kz-a-s03-exit', exitAnchorId: 'kz-a-s04-exit',
      respawnAnchorId: 'kz-a-s03-exit', survivalRole: KZ_ROUTE_SURVIVAL_ROLE.CHOICE,
      responseOptions: [KZ_ROUTE_RESPONSE_OPTION.STRAFE, KZ_ROUTE_RESPONSE_OPTION.JUMP],
      responseWindowTicks: 12, hitRecovery: KZ_ROUTE_HIT_RECOVERY.ADJACENT_SEGMENT,
      difficulty: difficulty(2, 2, 3, 3, 2, 2),
      branches: [
        {
          id: 'kz-branch-maze-fast', role: KZ_ROUTE_BRANCH_ROLE.FAST_EXPOSED,
          surfaceIds: ['kz-s04-fast-a', 'kz-s04-fast-b', 'kz-s04-merge'],
          pathAnchorIds: ['kz-a-s03-exit', 'kz-a-s04-fast-a', 'kz-a-s04-fast-b', 'kz-a-s04-exit'],
          recoveryAnchorId: 'kz-a-s03-exit', expectedTraversalTicks: 76, exposureWindowTicks: 12,
        },
        {
          id: 'kz-branch-maze-recovery', role: KZ_ROUTE_BRANCH_ROLE.SAFE_RECOVERY,
          surfaceIds: ['kz-s04-safe-a', 'kz-s04-safe-b', 'kz-s04-safe-c', 'kz-s04-merge'],
          pathAnchorIds: ['kz-a-s03-exit', 'kz-a-s04-safe-a', 'kz-a-s04-safe-b', 'kz-a-s04-safe-c', 'kz-a-s04-exit'],
          recoveryAnchorId: 'kz-a-s03-exit', expectedTraversalTicks: 151, exposureWindowTicks: 5,
        },
      ],
    },
    {
      id: 'kz-segment-05-narrow', kind: KZ_ROUTE_SEGMENT_KIND.NARROW_PATH,
      lessonId: 'kz.lesson.micro-correction', remixId: 'kz.remix.move-jump-alternation',
      surfaceIds: ['kz-s05-narrow'], pathAnchorIds: ['kz-a-s04-exit', 'kz-a-s05-exit'],
      entryAnchorId: 'kz-a-s04-exit', exitAnchorId: 'kz-a-s05-exit',
      respawnAnchorId: 'kz-a-s04-exit', survivalRole: KZ_ROUTE_SURVIVAL_ROLE.PRESSURE,
      responseOptions: [KZ_ROUTE_RESPONSE_OPTION.JUMP], responseWindowTicks: 6,
      hitRecovery: KZ_ROUTE_HIT_RECOVERY.ADJACENT_SEGMENT,
      difficulty: difficulty(2, 3, 3, 2, 3, 4), branches: [],
    },
    {
      id: 'kz-segment-06-wire', kind: KZ_ROUTE_SEGMENT_KIND.WIRE,
      lessonId: 'kz.lesson.long-correction', remixId: 'kz.remix.stable-or-edge-cut',
      surfaceIds: ['kz-s06-safe-a', 'kz-s06-safe-b', 'kz-s06-safe-c', 'kz-s06-fast-wire', 'kz-s06-finish'],
      pathAnchorIds: ['kz-a-s05-exit', 'kz-a-s06-safe-a', 'kz-a-s06-safe-b', 'kz-a-s06-safe-c', 'kz-a-s06-exit'],
      entryAnchorId: 'kz-a-s05-exit', exitAnchorId: 'kz-a-s06-exit',
      respawnAnchorId: 'kz-a-s05-exit', survivalRole: KZ_ROUTE_SURVIVAL_ROLE.CHOICE,
      responseOptions: [KZ_ROUTE_RESPONSE_OPTION.STRAFE], responseWindowTicks: 4,
      hitRecovery: KZ_ROUTE_HIT_RECOVERY.RESPAWN_ANCHOR,
      difficulty: difficulty(3, 4, 4, 2, 3, 3),
      branches: [
        {
          id: 'kz-branch-wire-recovery', role: KZ_ROUTE_BRANCH_ROLE.SAFE_RECOVERY,
          surfaceIds: ['kz-s06-safe-a', 'kz-s06-safe-b', 'kz-s06-safe-c', 'kz-s06-finish'],
          pathAnchorIds: ['kz-a-s05-exit', 'kz-a-s06-safe-a', 'kz-a-s06-safe-b', 'kz-a-s06-safe-c', 'kz-a-s06-exit'],
          recoveryAnchorId: 'kz-a-s05-exit', expectedTraversalTicks: 154, exposureWindowTicks: 4,
        },
        {
          id: 'kz-branch-wire-fast', role: KZ_ROUTE_BRANCH_ROLE.FAST_EXPOSED,
          surfaceIds: ['kz-s06-fast-wire', 'kz-s06-finish'],
          pathAnchorIds: ['kz-a-s05-exit', 'kz-a-s06-fast', 'kz-a-s06-exit'],
          recoveryAnchorId: 'kz-a-s05-exit', expectedTraversalTicks: 81, exposureWindowTicks: 8,
        },
      ],
    },
    {
      id: 'kz-segment-07-breather', kind: KZ_ROUTE_SEGMENT_KIND.BASIC_PLATFORM,
      lessonId: 'kz.lesson.reset-rhythm', remixId: 'kz.remix.safe-reorientation',
      surfaceIds: ['kz-s07-breather'], pathAnchorIds: ['kz-a-s06-exit', 'kz-a-s07-exit'],
      entryAnchorId: 'kz-a-s06-exit', exitAnchorId: 'kz-a-s07-exit',
      respawnAnchorId: 'kz-a-s06-exit', survivalRole: KZ_ROUTE_SURVIVAL_ROLE.SAFE,
      responseOptions: [KZ_ROUTE_RESPONSE_OPTION.HOLD, KZ_ROUTE_RESPONSE_OPTION.STRAFE, KZ_ROUTE_RESPONSE_OPTION.JUMP],
      responseWindowTicks: 14, hitRecovery: KZ_ROUTE_HIT_RECOVERY.SAME_SEGMENT,
      difficulty: difficulty(1, 1, 1, 1, 1, 2), branches: [],
    },
    {
      id: 'kz-segment-08-stairs', kind: KZ_ROUTE_SEGMENT_KIND.STAIRS,
      lessonId: 'kz.lesson.rising-rhythm', remixId: 'kz.remix.accelerating-three-step',
      surfaceIds: ['kz-s08-stair-a', 'kz-s08-stair-b', 'kz-s08-stair-c'],
      pathAnchorIds: ['kz-a-s07-exit', 'kz-a-s08-a', 'kz-a-s08-b', 'kz-a-s08-exit'],
      entryAnchorId: 'kz-a-s07-exit', exitAnchorId: 'kz-a-s08-exit',
      respawnAnchorId: 'kz-a-s07-exit', survivalRole: KZ_ROUTE_SURVIVAL_ROLE.PRESSURE,
      responseOptions: [KZ_ROUTE_RESPONSE_OPTION.STRAFE, KZ_ROUTE_RESPONSE_OPTION.JUMP],
      responseWindowTicks: 8, hitRecovery: KZ_ROUTE_HIT_RECOVERY.ADJACENT_SEGMENT,
      difficulty: difficulty(3, 3, 2, 2, 2, 3), branches: [],
    },
    {
      id: 'kz-segment-09-maze', kind: KZ_ROUTE_SEGMENT_KIND.MAZE,
      lessonId: 'kz.lesson.read-route-under-height', remixId: 'kz.remix.high-safe-or-low-fast',
      surfaceIds: ['kz-s09-fast-a', 'kz-s09-fast-b', 'kz-s09-safe-a', 'kz-s09-safe-b', 'kz-s09-safe-c', 'kz-s09-merge'],
      pathAnchorIds: ['kz-a-s08-exit', 'kz-a-s09-fast-a', 'kz-a-s09-fast-b', 'kz-a-s09-exit'],
      entryAnchorId: 'kz-a-s08-exit', exitAnchorId: 'kz-a-s09-exit',
      respawnAnchorId: 'kz-a-s08-exit', survivalRole: KZ_ROUTE_SURVIVAL_ROLE.CHOICE,
      responseOptions: [KZ_ROUTE_RESPONSE_OPTION.STRAFE, KZ_ROUTE_RESPONSE_OPTION.JUMP],
      responseWindowTicks: 10, hitRecovery: KZ_ROUTE_HIT_RECOVERY.ADJACENT_SEGMENT,
      difficulty: difficulty(3, 3, 4, 4, 2, 3),
      branches: [
        {
          id: 'kz-branch-high-maze-fast', role: KZ_ROUTE_BRANCH_ROLE.FAST_EXPOSED,
          surfaceIds: ['kz-s09-fast-a', 'kz-s09-fast-b', 'kz-s09-merge'],
          pathAnchorIds: ['kz-a-s08-exit', 'kz-a-s09-fast-a', 'kz-a-s09-fast-b', 'kz-a-s09-exit'],
          recoveryAnchorId: 'kz-a-s08-exit', expectedTraversalTicks: 70, exposureWindowTicks: 11,
        },
        {
          id: 'kz-branch-high-maze-recovery', role: KZ_ROUTE_BRANCH_ROLE.SAFE_RECOVERY,
          surfaceIds: ['kz-s09-safe-a', 'kz-s09-safe-b', 'kz-s09-safe-c', 'kz-s09-merge'],
          pathAnchorIds: ['kz-a-s08-exit', 'kz-a-s09-safe-a', 'kz-a-s09-safe-b', 'kz-a-s09-safe-c', 'kz-a-s09-exit'],
          recoveryAnchorId: 'kz-a-s08-exit', expectedTraversalTicks: 144, exposureWindowTicks: 5,
        },
      ],
    },
    {
      id: 'kz-segment-10-gap', kind: KZ_ROUTE_SEGMENT_KIND.GAP,
      lessonId: 'kz.lesson.long-gap-after-choice', remixId: 'kz.remix.commit-after-route-read',
      surfaceIds: ['kz-s10-landing'], pathAnchorIds: ['kz-a-s09-exit', 'kz-a-s10-exit'],
      entryAnchorId: 'kz-a-s09-exit', exitAnchorId: 'kz-a-s10-exit',
      respawnAnchorId: 'kz-a-s09-exit', survivalRole: KZ_ROUTE_SURVIVAL_ROLE.RECOVERY,
      responseOptions: [KZ_ROUTE_RESPONSE_OPTION.JUMP], responseWindowTicks: 7,
      hitRecovery: KZ_ROUTE_HIT_RECOVERY.RESPAWN_ANCHOR,
      difficulty: difficulty(4, 4, 2, 2, 3, 3), branches: [],
    },
    {
      id: 'kz-segment-11-narrow', kind: KZ_ROUTE_SEGMENT_KIND.NARROW_PATH,
      lessonId: 'kz.lesson.micro-correction-under-pressure', remixId: 'kz.remix.narrow-after-long-gap',
      surfaceIds: ['kz-s11-narrow'], pathAnchorIds: ['kz-a-s10-exit', 'kz-a-s11-exit'],
      entryAnchorId: 'kz-a-s10-exit', exitAnchorId: 'kz-a-s11-exit',
      respawnAnchorId: 'kz-a-s10-exit', survivalRole: KZ_ROUTE_SURVIVAL_ROLE.PRESSURE,
      responseOptions: [KZ_ROUTE_RESPONSE_OPTION.STRAFE, KZ_ROUTE_RESPONSE_OPTION.JUMP],
      responseWindowTicks: 5, hitRecovery: KZ_ROUTE_HIT_RECOVERY.ADJACENT_SEGMENT,
      difficulty: difficulty(3, 4, 4, 3, 3, 4), branches: [],
    },
    {
      id: 'kz-segment-12-wire', kind: KZ_ROUTE_SEGMENT_KIND.WIRE,
      lessonId: 'kz.lesson.final-route-control', remixId: 'kz.remix.recovery-zigzag-or-exposed-wire',
      surfaceIds: ['kz-s12-safe-a', 'kz-s12-safe-b', 'kz-s12-safe-c', 'kz-s12-fast-wire', 'kz-s12-finish'],
      pathAnchorIds: ['kz-a-s11-exit', 'kz-a-s12-safe-a', 'kz-a-s12-safe-b', 'kz-a-s12-safe-c', 'kz-a-finish'],
      entryAnchorId: 'kz-a-s11-exit', exitAnchorId: 'kz-a-finish',
      respawnAnchorId: 'kz-a-s11-exit', survivalRole: KZ_ROUTE_SURVIVAL_ROLE.CHOICE,
      responseOptions: [KZ_ROUTE_RESPONSE_OPTION.STRAFE, KZ_ROUTE_RESPONSE_OPTION.JUMP],
      responseWindowTicks: 4, hitRecovery: KZ_ROUTE_HIT_RECOVERY.RESPAWN_ANCHOR,
      difficulty: difficulty(4, 4, 4, 4, 4, 4),
      branches: [
        {
          id: 'kz-branch-final-wire-recovery', role: KZ_ROUTE_BRANCH_ROLE.SAFE_RECOVERY,
          surfaceIds: ['kz-s12-safe-a', 'kz-s12-safe-b', 'kz-s12-safe-c', 'kz-s12-finish'],
          pathAnchorIds: ['kz-a-s11-exit', 'kz-a-s12-safe-a', 'kz-a-s12-safe-b', 'kz-a-s12-safe-c', 'kz-a-finish'],
          recoveryAnchorId: 'kz-a-s11-exit', expectedTraversalTicks: 148, exposureWindowTicks: 4,
        },
        {
          id: 'kz-branch-final-wire-fast', role: KZ_ROUTE_BRANCH_ROLE.FAST_EXPOSED,
          surfaceIds: ['kz-s12-fast-wire', 'kz-s12-finish'],
          pathAnchorIds: ['kz-a-s11-exit', 'kz-a-s12-fast', 'kz-a-finish'],
          recoveryAnchorId: 'kz-a-s11-exit', expectedTraversalTicks: 74, exposureWindowTicks: 9,
        },
      ],
    },
  ],
  supplyPoints: [
    { equipmentSpawnPointId: 'kz-supply-01', anchorId: 'kz-a-s01-supply', segmentId: 'kz-segment-01-platform' },
    { equipmentSpawnPointId: 'kz-supply-02', anchorId: 'kz-a-s02-supply', segmentId: 'kz-segment-02-gap' },
    { equipmentSpawnPointId: 'kz-supply-03', anchorId: 'kz-a-s03-supply', segmentId: 'kz-segment-03-stairs' },
    { equipmentSpawnPointId: 'kz-supply-04', anchorId: 'kz-a-s04-supply', segmentId: 'kz-segment-04-maze' },
    { equipmentSpawnPointId: 'kz-supply-05', anchorId: 'kz-a-s05-supply', segmentId: 'kz-segment-05-narrow' },
    { equipmentSpawnPointId: 'kz-supply-06', anchorId: 'kz-a-s06-supply', segmentId: 'kz-segment-06-wire' },
    { equipmentSpawnPointId: 'kz-supply-07', anchorId: 'kz-a-s07-supply', segmentId: 'kz-segment-07-breather' },
    { equipmentSpawnPointId: 'kz-supply-08', anchorId: 'kz-a-s08-supply', segmentId: 'kz-segment-08-stairs' },
    { equipmentSpawnPointId: 'kz-supply-09', anchorId: 'kz-a-s09-supply', segmentId: 'kz-segment-09-maze' },
    { equipmentSpawnPointId: 'kz-supply-10', anchorId: 'kz-a-s10-supply', segmentId: 'kz-segment-10-gap' },
    { equipmentSpawnPointId: 'kz-supply-11', anchorId: 'kz-a-s11-supply', segmentId: 'kz-segment-11-narrow' },
    { equipmentSpawnPointId: 'kz-supply-12', anchorId: 'kz-a-s12-supply', segmentId: 'kz-segment-12-wire' },
  ],
  survivalLinks: [
    { fromSegmentId: 'kz-segment-01-platform', toSegmentId: 'kz-segment-02-gap' },
    { fromSegmentId: 'kz-segment-02-gap', toSegmentId: 'kz-segment-01-platform' },
    { fromSegmentId: 'kz-segment-02-gap', toSegmentId: 'kz-segment-03-stairs' },
    { fromSegmentId: 'kz-segment-03-stairs', toSegmentId: 'kz-segment-02-gap' },
    { fromSegmentId: 'kz-segment-03-stairs', toSegmentId: 'kz-segment-04-maze' },
    { fromSegmentId: 'kz-segment-04-maze', toSegmentId: 'kz-segment-03-stairs' },
    { fromSegmentId: 'kz-segment-04-maze', toSegmentId: 'kz-segment-05-narrow' },
    { fromSegmentId: 'kz-segment-05-narrow', toSegmentId: 'kz-segment-04-maze' },
    { fromSegmentId: 'kz-segment-05-narrow', toSegmentId: 'kz-segment-06-wire' },
    { fromSegmentId: 'kz-segment-06-wire', toSegmentId: 'kz-segment-05-narrow' },
    { fromSegmentId: 'kz-segment-06-wire', toSegmentId: 'kz-segment-07-breather' },
    { fromSegmentId: 'kz-segment-07-breather', toSegmentId: 'kz-segment-06-wire' },
    { fromSegmentId: 'kz-segment-07-breather', toSegmentId: 'kz-segment-08-stairs' },
    { fromSegmentId: 'kz-segment-08-stairs', toSegmentId: 'kz-segment-07-breather' },
    { fromSegmentId: 'kz-segment-08-stairs', toSegmentId: 'kz-segment-09-maze' },
    { fromSegmentId: 'kz-segment-09-maze', toSegmentId: 'kz-segment-08-stairs' },
    { fromSegmentId: 'kz-segment-09-maze', toSegmentId: 'kz-segment-10-gap' },
    { fromSegmentId: 'kz-segment-10-gap', toSegmentId: 'kz-segment-09-maze' },
    { fromSegmentId: 'kz-segment-10-gap', toSegmentId: 'kz-segment-11-narrow' },
    { fromSegmentId: 'kz-segment-11-narrow', toSegmentId: 'kz-segment-10-gap' },
    { fromSegmentId: 'kz-segment-11-narrow', toSegmentId: 'kz-segment-12-wire' },
    { fromSegmentId: 'kz-segment-12-wire', toSegmentId: 'kz-segment-11-narrow' },
  ],
});

export const ARENA_V2_KZ_BASE_MOBILITY_ENVELOPE_CANDIDATE_V1:
KzRouteMobilityEnvelopeV1 = Object.freeze({
  maximumStepHeight: 0.4,
  maximumJumpGap: 2.25,
  maximumJumpRise: 0.65,
  maximumSafeDrop: 1.5,
  anchorGroundTolerance: 0.001,
});

export const ARENA_V2_KZ_BASE_MAP_STATIC_VALIDATION_CANDIDATE_V1 =
  validateKzRouteMapCandidateV1(
    ARENA_V2_KZ_BASE_ROUTE_DEFINITION_CANDIDATE_V2,
    ARENA_V2_KZ_BASE_MAP_DEFINITION_CANDIDATE_V1,
    ARENA_V2_KZ_BASE_MOBILITY_ENVELOPE_CANDIDATE_V1,
  );

export const ARENA_V2_KZ_BASE_MAP_CANDIDATE_V1 = Object.freeze({
  status: 'production-unreachable' as const,
  hardGate: false as const,
  mapDefinition: ARENA_V2_KZ_BASE_MAP_DEFINITION_CANDIDATE_V1,
  routeDefinition: ARENA_V2_KZ_BASE_ROUTE_DEFINITION_CANDIDATE_V2,
  raceFinishCapability: Object.freeze({
    capabilityId: ARENA_V2_RACE_FINISH_GATE_CAPABILITY_ID_V1,
    anchorId: ARENA_V2_KZ_BASE_ROUTE_DEFINITION_CANDIDATE_V2.finishAnchorId,
  }),
  mobilityEnvelope: ARENA_V2_KZ_BASE_MOBILITY_ENVELOPE_CANDIDATE_V1,
  staticValidation: ARENA_V2_KZ_BASE_MAP_STATIC_VALIDATION_CANDIDATE_V1,
});
